name: Android Build

on:
  push:
    branches:
      - main # atau ganti dengan nama cabang yang Anda gunakan
  pull_request:
    branches:
      - main # atau ganti dengan nama cabang yang Anda gunakan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://services.gradle.org/distributions/gradle-7.5-bin.zip
        unzip gradle-7.5-bin.zip
        sudo mv gradle-7.5 /opt/gradle
        sudo ln -s /opt/gradle/bin/gradle /usr/bin/gradle
    
    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk
